export default {
	SET_LOADING: 'SET_LOADING',
	SET_VEHICLE_LIST: 'SET_VEHICLE_LIST',
	SET_VEHICLE_HAS_ERROR: 'SET_VEHICLE_HAS_ERROR',
	SET_MAP_LIST: 'SET_MAP_LIST',
	SET_MAP_HAS_ERROR: 'SET_MAP_HAS_ERROR',
};
